resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: |
     **\*Tests*.dll
     !**\obj\**
    codeCoverageEnabled: true

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true
  
- script: dotnet run -- Structurizr:Key=fa8ec9d2-fdea-4663-9ff4-14be9ca80e37 Structurizr:Secret=77335096-84be-47e1-9ec2-e4f3cfd4bd41 Structurizr:WorkspaceId=40713
  displayName: 'Publish Functions architecture to Structurizr'
  workingDirectory: IotReferenceArchitectureFunctions

    
