resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: |
     **\*Tests*.dll
     !**\obj\**
    codeCoverageEnabled: true

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true
  
- script: dotnet run -- Structurizr:Key=$(Structurizr.Key) Structurizr:Secret=$(Structurizr.Secret) Structurizr:WorkspaceId=$(Structurizr.WorkspaceId)
  displayName: 'Publish Functions architecture to Structurizr'
  workingDirectory: IotReferenceArchitectureFunctions\IotReferenceArchitectureFunctions.Architecture

    
